-artifact@v2
        with:
          name: Playwright test report
          path: |
            playwright_tests/allure-report
      - name: Playwright Test Status
        if: env.TESTS_FAILED == 'true'
        run: exit 1
